CREATE TABLE audiobook (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           title VARCHAR(50) NOTNULL,
                           category VARCHAR(50) NOTNULL,
                           author VARCHAR(50) NOTNULL,
                           narrator VARCHAR(50) NOTNULL,
                           release_date VARCHAR(25) NOTNULL
);