CREATE TABLE audiobook (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           title NOTNULL VARCHAR(50),
                           category NOTNULL VARCHAR(50),
                           author NOTNULL VARCHAR(50),
                           narrator NOTNULL VARCHAR(50),
                           release_date NOTNULL VARCHAR(25)
);