CREATE TABLE audiobook
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(50) NOT NULL,
    category     VARCHAR(50) NOT NULL,
    author       VARCHAR(50) NOT NULL,
    narrator     VARCHAR(50) NOT NULL,
    release_date VARCHAR(25) NOT NULL
);